name: LibCommand
version: 2.0.0-dev

authors:
  - ImperaZim

api: 5.0.0
main: imperazim\command\LibCommand
load: STARTUP

depend:
  - LibPacket

extensions:
  Core: ">=8.2"

autoload:
  psr-4:
    imperazim\\command\\: src/imperazim/command
