<?php

declare(strict_types=1);

namespace pocketmine\utils {
    final class TextFormat { public const RESET=''; public const BOLD=''; public const AQUA=''; public const BLACK=''; public const BLUE=''; public const DARK_AQUA=''; public const DARK_BLUE=''; public const DARK_GRAY=''; public const DARK_GREEN=''; public const DARK_PURPLE=''; public const DARK_RED=''; public const GOLD=''; public const GRAY=''; public const GREEN=''; public const LIGHT_PURPLE=''; public const RED=''; public const WHITE=''; public const YELLOW=''; }
}

namespace pocketmine\permission { final class DefaultPermissions { public const ROOT_USER = 'pocketmine.group.operator'; } }

namespace pocketmine\plugin {
    interface Logger { public function warning(string $message): void; public function notice(string $message): void; public function info(string $message): void; public function debug(string $message): void; public function error(string $message): void; }
    final class NullLogger implements Logger { public function warning(string $message): void {} public function notice(string $message): void {} public function info(string $message): void {} public function debug(string $message): void {} public function error(string $message): void {} }
    final class PluginDescription { public function getName(): string { return 'Plugin'; } public function getVersion(): string { return '1.0.0'; } }
    interface Plugin { public function getName(): string; public function getLogger(): Logger; public function getServer(): \pocketmine\Server; public function getDescription(): PluginDescription; public function getScheduler(): \pocketmine\scheduler\TaskScheduler; }
    abstract class PluginBase implements Plugin { public function getName(): string { return static::class; } public function getLogger(): Logger { return new NullLogger(); } public function getServer(): \pocketmine\Server { return \pocketmine\Server::getInstance(); } public function getDescription(): PluginDescription { return new PluginDescription(); } public function getScheduler(): \pocketmine\scheduler\TaskScheduler { return new \pocketmine\scheduler\TaskScheduler(); } }
}

namespace pocketmine\command {
    interface CommandSender { public function sendMessage(string $message): void; public function getName(): string; public function hasPermission(string $permission): bool; public function getPosition(): \pocketmine\world\Position; public function getWorld(): \pocketmine\world\World; public function getUniqueId(): string; }
    class Command { public function __construct(string $name = '', string $description = '', string $usageMessage = '', array $aliases = []) {} public function setPermission(?string $permission): void {} public function getPermission(): ?string { return null; } public function getName(): string { return 'command'; } public function getDescription(): string { return ''; } public function setDescription(string $description): void {} public function setAliases(array $aliases): void {} }
}

namespace pocketmine\event { interface Listener {} class Event {} final class EventPriority { public const LOWEST=0; public const LOW=1; public const NORMAL=2; public const HIGH=3; public const HIGHEST=4; public const MONITOR=5; } }
namespace pocketmine\event\player { final class PlayerChatEvent extends \pocketmine\event\Event { public function getPlayer(): \pocketmine\player\Player { return new \pocketmine\player\Player(); } public function cancel(): void {} public function getMessage(): string { return ''; } } }

namespace pocketmine\math { class Vector3 { public function __construct(public float|int $x=0, public float|int $y=0, public float|int $z=0) {} public function distance(self $pos): float { return 0.0; } } }
namespace pocketmine\world { class World { public function getDisplayName(): string { return 'world'; } public function getFolderName(): string { return 'world'; } public function getEntities(): array { return []; } } class Position extends \pocketmine\math\Vector3 { public function __construct(float|int $x=0, float|int $y=0, float|int $z=0, private ?World $world=null) { parent::__construct($x,$y,$z); } public function getWorld(): World { return $this->world ?? new World(); } } class WorldManager { public function getWorldByName(string $name): ?World { return null; } public function getWorlds(): array { return []; } } }
namespace pocketmine\entity { class Entity { public function getName(): string { return 'Entity'; } public function getWorld(): \pocketmine\world\World { return new \pocketmine\world\World(); } public function getPosition(): \pocketmine\world\Position { return new \pocketmine\world\Position(); } } }
namespace pocketmine\player { enum GameMode { case SURVIVAL; case CREATIVE; case ADVENTURE; case SPECTATOR; } class Player extends \pocketmine\entity\Entity implements \pocketmine\command\CommandSender { public function __construct(private string $name='Player') {} public function sendMessage(string $message): void {} public function getName(): string { return $this->name; } public function hasPermission(string $permission): bool { return true; } public function getWorld(): \pocketmine\world\World { return new \pocketmine\world\World(); } public function getPosition(): \pocketmine\world\Position { return new \pocketmine\world\Position(); } public function getUniqueId(): string { return $this->name; } public function getGamemode(): GameMode { return GameMode::SURVIVAL; } public function isConnected(): bool { return true; } } }

namespace pocketmine { final class CommandMap { public function register(string $fallbackPrefix, \pocketmine\command\Command $command): bool { return true; } public function unregister(\pocketmine\command\Command $command): void {} } final class ConsoleSender implements \pocketmine\command\CommandSender { public function sendMessage(string $message): void {} public function getName(): string { return 'CONSOLE'; } public function hasPermission(string $permission): bool { return true; } public function getPosition(): \pocketmine\world\Position { return new \pocketmine\world\Position(); } public function getWorld(): \pocketmine\world\World { return new \pocketmine\world\World(); } public function getUniqueId(): string { return 'console'; } } final class AsyncPool { public function submitTask(\pocketmine\scheduler\AsyncTask $task): int { return 0; } } final class Server { private static ?self $instance = null; public static function getInstance(): self { return self::$instance ??= new self(); } public function getCommandMap(): CommandMap { return new CommandMap(); } public function getLogger(): \pocketmine\plugin\Logger { return new \pocketmine\plugin\NullLogger(); } public function getWorldManager(): \pocketmine\world\WorldManager { return new \pocketmine\world\WorldManager(); } public function getOnlinePlayers(): array { return []; } public function getPlayerExact(string $name): ?\pocketmine\player\Player { return null; } public function getPlayerByPrefix(string $name): ?\pocketmine\player\Player { return null; } public function getConsoleSender(): ConsoleSender { return new ConsoleSender(); } public function getAsyncPool(): AsyncPool { return new AsyncPool(); } } }

namespace pocketmine\scheduler { class Task {} final class TaskHandler { public function cancel(): void {} } final class TaskScheduler { public function scheduleDelayedTask(Task $task, int $delay): TaskHandler { return new TaskHandler(); } public function scheduleRepeatingTask(Task $task, int $period): TaskHandler { return new TaskHandler(); } public function cancelTask(int $taskId): void {} } final class ClosureTask extends Task { public function __construct(callable $closure) {} } abstract class AsyncTask { public function storeLocal(string $key, mixed $value): void {} public function fetchLocal(string $key): mixed { return null; } public function setResult(mixed $result): void {} public function getResult(): mixed { return null; } abstract public function onRun(): void; public function onCompletion(): void {} } }

namespace pocketmine\item { class Item {} final class LegacyStringToItemParser { public static function getInstance(): self { return new self(); } public function parse(string $input): ?Item { return new Item(); } } final class StringToItemParser { public static function getInstance(): self { return new self(); } public function parse(string $input): ?Item { return new Item(); } } }

namespace pocketmine\network\mcpe { final class NetworkBroadcastUtils { public static function broadcastPackets(array $targets, array $packets): void {} } }
namespace pocketmine\network\mcpe\protocol { class ClientboundPacket {} class DataPacket extends ClientboundPacket {} final class AvailableCommandsPacket extends DataPacket { public const NETWORK_ID=76; public const ARG_FLAG_ENUM=0x200000; public const ARG_TYPE_VALUE=0; public const ARG_TYPE_INT=1; public const ARG_TYPE_FLOAT=2; public const ARG_TYPE_STRING=3; public const ARG_TYPE_TARGET=4; public const ARG_TYPE_POSITION=5; public array $commandData = []; } final class UpdateSoftEnumPacket extends ClientboundPacket { public const TYPE_ADD=0; public const TYPE_REMOVE=1; public const TYPE_SET=2; public string $enumName=''; public array $values=[]; public int $type=self::TYPE_SET; } }
namespace pocketmine\network\mcpe\protocol\serializer { final class AvailableCommandsPacketDisassembler { public static function disassemble(\pocketmine\network\mcpe\protocol\AvailableCommandsPacket $packet): array { return []; } } final class AvailableCommandsPacketAssembler { public static function assemble(array $commandData, array $dynamicEnums = [], array $softEnums = []): \pocketmine\network\mcpe\protocol\AvailableCommandsPacket { return new \pocketmine\network\mcpe\protocol\AvailableCommandsPacket(); } } }
namespace pocketmine\network\mcpe\protocol\types\command { final class CommandHardEnum { public function __construct(private string $name, private array $values = []) {} public function getName(): string { return $this->name; } public function getValues(): array { return $this->values; } } final class CommandSoftEnum { public function __construct(private string $name, private array $values = []) {} public function getName(): string { return $this->name; } public function getValues(): array { return $this->values; } } final class CommandParameter { public ?CommandHardEnum $enum = null; public string $paramName=''; public int $paramType=0; public bool $isOptional=false; public static function standard(string $name, int $type, int $flags = 0, bool $optional = false): self { $p = new self(); $p->paramName=$name; $p->paramType=$type; $p->isOptional=$optional; return $p; } public static function enum(string $name, CommandHardEnum $enum, int $flags = 0, bool $optional = false): self { $p = self::standard($name, 0, $flags, $optional); $p->enum = $enum; return $p; } public static function softEnum(string $name, CommandSoftEnum $enum, int $flags = 0, bool $optional = false): self { return self::standard($name, 0, $flags, $optional); } } final class CommandOverload { public function __construct(public bool $chaining = false, public array $parameters = []) {} } }

namespace imperazim\packet { final class LibPacket { public static function createInterceptor(\pocketmine\plugin\PluginBase $plugin, int $priority = 0): \imperazim\packet\interceptor\PacketInterceptorInterface { return new \imperazim\packet\interceptor\NullPacketInterceptor(); } } }
namespace imperazim\packet\interceptor { interface PacketInterceptorInterface { public function registerOutgoing(\imperazim\packet\handler\PacketHandlerInterface $handler): void; public function unregisterOutgoing(\imperazim\packet\handler\PacketHandlerInterface $handler): void; } final class NullPacketInterceptor implements PacketInterceptorInterface { public function registerOutgoing(\imperazim\packet\handler\PacketHandlerInterface $handler): void {} public function unregisterOutgoing(\imperazim\packet\handler\PacketHandlerInterface $handler): void {} } }
namespace imperazim\packet\handler { interface PacketHandlerInterface { public function getPacketIds(): array; } abstract class PacketHandler implements PacketHandlerInterface { public function getPacketIds(): array { return []; } } }
